---
- name: Prepare
  hosts: sonarqube
  become: true
  vars:
    sonar_version: 7.9.6
    sonar_plugins:
      - name: "sonar-l10n-pt"
        version: "6.4"
        commercial: false
        url: "https://github.com/felipebz/sonar-l10n-pt/releases/download/v6.4/sonar-l10n-pt-plugin-6.4.jar"
      - name: "sonar-html-plugin"
        version: "3.2.0.2082"
        commercial: false
      - name: "ansible"
        version: "2.4.0"
        marketplace: true

  # roles:
  #   - name: buluma.bootstrap

  pre_tasks:
    - name: install openjdk (redhat)
      ansible.builtin.package:
        name: java-11-openjdk
        state: present
      when: ansible_facts['os_family'] == "RedHat"
    - name: install openjdk (debian)
      ansible.builtin.apt:
        name: openjdk-11-jdk
        state: present
      when: ansible_facts['os_family'] == "Debian"

  roles:
    - role: buluma.sonarqube

  tasks:
    # - name: "ensure apt cache is up to date"
    #   become: true
    #   ansible.builtin.apt:
    #     update_cache: yes
    #   when: ansible_distribution == 'Ubuntu'

    - name: "install package dependencies"
      ansible.builtin.package:
        name: "{{ item }}"
        state: "present"
      with_items:
        - unzip