sudo: required
language: python
services:
  - docker

install:
  - pip install ansible-lint

script:
  - ansible-lint playbook.yml

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
