---
dependency:
  name: galaxy
  requirements_file: requirements.yml
driver:
  name: vagrant
vagrant:
  platforms:
    - name: redesign/centos7
      box: "redesign/centos7"
      # save time in test runs
  raw_config_args:
    - 'vm.synced_folder ".", "/vagrant", disabled: true'
    - 'vbguest.auto_update = false'
    - 'ssh.insert_key = false'
  providers:
    - name: virtualbox
      type: virtualbox
      options:
        memory: 4096
        cpus: 2
  instances:
    - name: vm
      ansible_groups:
        - group1
verifier:
  name: goss
molecule:
  test:
  # sequence of commands to run when performing `molecule test`
    sequence:
      - syntax
      - create
      - converge
      - idempotence
      - verify

  # directories to ignore when doing trailing whitespace checks
  ignore_paths:
    - .git
    - .vagrant
    - .molecule
    - .tox
