---
- hosts: all

  vars_files:
    - defaults/main.yml
    - vars/main.yml

  vars:
    - artifactory_database: postgres
    - vault_postgres_user: test_db_user
    - vault_base_postgres_pass: test_password

  roles:
    - role: dockpack.base_postgres
      when: artifactory_database == 'postgresql'
    - role: dockpack.base_goss
    - role: artifactory
