pipeline {
    agent any

    environment {
        ANSIBLE_CONFIG="${WORKSPACE}/deploy/ansible.cfg"
    }

    parameters {
      string(name: 'inventory', defaultValue: 'dev',  description: 'This is the inventory file for the environment to deploy configuration')
    }

    stages(){

        stage('Checkout code from GitHub'){
            steps{
             checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[credentialsId: 'GitHub token', url: 'https://github.com/dapetoo/ansible-config-mgt.git']])
            }
        }

        stage('Prepare Ansible For Execution') {
            steps {
                sh 'echo ${WORKSPACE}' 
                sh 'sed -i "3 a roles_path=${WORKSPACE}/roles" ${WORKSPACE}/deploy/ansible.cfg'  
            }
        }

        stage('Run Ansible Playbook') {
            steps {
                sh 'echo Running playbooks' 
                ansiblePlaybook credentialsId: 'ssh-key', installation: 'ansible', disableHostKeyChecking: true, inventory: 'inventory/dev', playbook: 'playbooks/site.yml'
                // sh 'sed -i "3 a roles_path=${WORKSPACE}/roles" ${WORKSPACE}/deploy/ansible.cfg'  
                // sh 'ansible-playbook -i ${WORKSPACE}/inventory/dev  ${WORKSPACE}/playbooks/site.yml'
            }
        }
    }
}