---

- name: 'ensure artifactory_data_filestore_path variable is set'
  fail:
    msg: "artifactory_data_filestore_path is required with derby storage strategy"
  when: not artifactory_data_filestore_path
  tags:
    - artifactory

- name: 'ensure artifactory_data_derby_path variable is set'
  fail:
    msg: "artifactory_data_derby_path is required with derby storage strategy"
  when: not artifactory_data_derby_path
  tags:
    - artifactory

- name: 'ensure filestore folder exists'
  file:
    path: "{{ artifactory_data_filestore_path }}"
    owner: "{{ artifactory_username }}"
    group: "{{ artifactory_username }}"
    state: directory
  tags:
    - artifactory

- name: 'ensure derby folder exists'
  file:
    path: "{{ artifactory_data_derby_path }}"
    owner: "{{ artifactory_username }}"
    group: "{{ artifactory_username }}"
    state: directory
  tags:
    - artifactory
