---

- name: 'make sure MySQL-python is installed'
  when: ansible_os_family == 'RedHat' and artifactory_database == 'mysql'
  yum:
    name: MySQL-python
    state: installed
  retries: 3
  register: result
  until: result is succeeded
  tags:
    - python

- name: 'make sure mysql dependencies are installed'
  package:
    name: python-mysqldb
    state: installed
  retries: 3
  register: result
  until: result is succeeded
  when: ansible_os_family == 'Debian' and artifactory_database == 'mysql'
  tags:
    - python

- name: 'create artifactory database in mysql'
  when: artifactory_database == 'mysql'
  mysql_db:
    name: artdb
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: 'create artifactory database user in mysql'
  when: artifactory_database == 'mysql'
  mysql_user:
    name: "{{ artifactory_username }}"
    priv: "artdb.*:ALL"
    password: "{{ artifactory_password }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: 'verify presence of jdbc connector for mysql'
  when: artifactory_database == 'mysql'
  stat:
    path: "{{ artifactory_home }}/tomcat/lib/{{ mysql_jdbc_base }}-bin.jar"
  register: jdbc_installed

- name: 'download jdbc connector for mysql'
  unarchive:
    copy: no
    src: "{{ mysql_jdbc_url }}"
    dest: /tmp
    validate_certs: no
  retries: 3
  when: not jdbc_installed.stat.exists and artifactory_database == 'mysql'

- name: 'enable jdbc connector for mysql'
  command: mv /tmp/{{ mysql_jdbc_base }}/{{ mysql_jdbc_base }}-bin.jar {{ artifactory_home }}/tomcat/lib
  when: not jdbc_installed.stat.exists and artifactory_database == 'mysql'


- name: 'seboolean allow_user_mysql_connect'
  seboolean:
    name: allow_user_mysql_connect
    state: yes
    persistent: yes
  when: ansible_selinux.status == "enabled" and artifactory_database == 'mysql'
  ignore_errors: yes
