---

- name: 'make sure postgres dependencies are installed'
  package:
    name: python-psycopg2
    state: installed
  retries: 3
  register: result
  until: result is succeeded
  when: ansible_os_family == 'RedHat' or ansible_os_family == 'Debian'
  tags:
    - python

- name: 'create artifactory database user in postgres'
  when: artifactory_database == 'postgresql'
  become: yes
  become_user: postgres
  postgresql_user:
    name: "{{ artifactory_username }}"
    password: "{{ artifactory_password }}"
  tags:
    - users

- name: 'create artifactory database in postgres'
  when: artifactory_database == 'postgresql'
  become: yes
  become_user: postgres
  postgresql_db:
    name: artifactory
    owner: "{{ artifactory_username }}"
    template: 'template0'
    encoding: 'UTF-8'

- name: 'download jdbc connector for postgres'
  when: artifactory_database == 'postgresql'
  get_url:
    url: "{{ postgres_jdbc_url }}"
    dest: "{{ artifactory_home }}/tomcat/lib"
  retries: 3
  register: jdbc_installed
